apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yawsir
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eldios/yawsir.git
    path: helm/yawsir
    targetRevision: HEAD
    helm:
      values: |
        app:
          message: "Hello"
  destination:
    server: https://kubernetes.default.svc
    namespace: yawsir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
