apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yawsir
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eldios/yawsir.git
    path: argo/yawsir
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
