name: Test, Build and Publish

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: "Cargo check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - uses: "dtolnay/rust-toolchain@master"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - name: "Run Cargo check"
        run: "cargo check"

  test:
    name: "Cargo test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - uses: "dtolnay/rust-toolchain@master"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - name: "Run Cargo test"
        run: "cargo test"

  fmt:
    name: "Cargo format"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - uses: "dtolnay/rust-toolchain@master"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - run: "rustup component add rustfmt"

      - name: "Run Cargo FMT --all"
        run: "cargo fmt --all -- --check"

  clippy:
    name: "Cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - uses: "dtolnay/rust-toolchain@master"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - run: "rustup component add clippy"

      - name: "Run Cargo clippy"
        run: "cargo clippy -- -D warnings"

  get-tag:
    name: "Get Tag From Package Version"
    runs-on: "ubuntu-latest"
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.PKG_VERSION }}
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get tag"
        id: "pkg-version"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-24.04
    needs:
      - check
      - test
      - fmt
      - clippy
      - get-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "stable"
          override: true

      - uses: "actions-rs/cargo@v1"
        with:
          command: "build"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build and push Docker image (latest and Cargo tag)"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:v${{ needs.get-tag.outputs.pkg-version }}
          labels: ${{ steps.meta.outputs.labels }}
