name: "Terraform Infra CI"

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

env:
  FORCE_COLOR: 3

jobs:
  check-terraform-format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: terraform fmt -check -recursive -write=false

  terraform-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        # https://github.com/bridgecrewio/checkov-action/blob/v12/action.yml
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          directory: terraform/
          output_format: "github_failed_only"

  pr-ready-for-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: ["check-terraform-format", "terraform-quality"]
    if: >-
      always() &&
      needs.check-terraform-format.result == 'success' &&
      needs.terraform-quality.result == 'success'
    steps:
      - run: echo "PR ready to be merged"
